[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python combined_runner.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "latecorners" 