#!/usr/bin/env python3

print('🎯 CORNER BETTING SYSTEM - QUICK STATS REFERENCE')
print('='*70)
print()

print('📊 TIER 1 - CORE PREDICTION STATS (Must Have):')
print('   Type 34: Corners              Weight: ×5    (100% available)')
print('   Type 49: Shots Inside Box     Weight: ×4    (Premium only) ⭐')
print('   Type 60: Crosses              Weight: ×2    (Premium only) ⭐')
print()

print('🔥 TIER 2 - PRESSURE INDICATORS (High Value):')
print('   Type 44: Dangerous Attacks    Weight: ×0.3  (100% available)')
print('   Type 51: Offsides             Weight: ×4    (60% available)')
print('   Type 42: Shots Total          Weight: ×1.5  (100% available)')
print()

print('⚡ TIER 3 - TEMPO INDICATORS (Supporting):')
print('   Type 56: Free Kicks           Weight: ×0.8  (60% available)')
print('   Type 55: Throw Ins            Weight: ×0.4  (40% available)')
print('   Type 43: Attacks              Weight: ×0.1  (100% available)')
print()

print('📈 TIER 4 - CONTROL STATS (Context):')
print('   Type 45: Ball Possession %    Weight: ×0.2  (60% available)')
print('   Type 41: Shots Off Target     Weight: calc  (100% available)')
print()

print('🆕 TIER 5 - PREMIUM EXCLUSIVE (Bonus):')
print('   Type 53: Yellow Cards         Weight: bonus (Premium only)')
print('   Type 62: Fouls                Weight: bonus (Premium only)')
print('   Type 27264: Long Passes       Weight: bonus (Top-tier only)')
print()

print('🚀 FINAL CALCULATION:')
print('   Base Score = All weighted stats combined')
print('   Quality Multiplier = 1 + (league_quality/200)')
print('   FINAL SCORE = Base Score × Quality Multiplier')
print()

print('🎯 RECOMMENDATION THRESHOLDS:')
print('   Score ≥60 + Premium Stats = 🟢 STRONG BUY')
print('   Score ≥40 + Good Stats    = 🟡 BUY')
print('   Score ≥25                 = 🟠 WEAK BUY')
print('   Score <25                 = 🔴 AVOID')
print()

print('💡 OPTIMAL RANGES FOR STRONG BUY:')
print('   Corners: 6+ total')
print('   Shots Inside Box: 8+ OR >40% ratio')
print('   Crosses: 20+ total')
print('   Dangerous Attacks: 40+')
print('   Offsides: 3+')
print('   Quality Score: 120+')
print()

print('📊 LEAGUE TIER BREAKDOWN:')
print('   🏆 PREMIUM (Score 120-140): All stats available')
print('   🥈 STANDARD (Score 40-80): Core stats only')
print('   🥉 LOW (Score 0-40): Limited/unreliable data') 